# This is a generated file. Not intended for manual editing.
services:
  stockapp.api:
    build:
      context: "C:\\Users\\arthu\\Desktop\\back-novo\\dbcamp-estoque-app"
      dockerfile: "StockApp.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/StockApp.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "stockapp.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\arthu\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\arthu\\Desktop\\back-novo\\dbcamp-estoque-app\\StockApp.API:/app:rw"
    - "C:\\Users\\arthu\\Desktop\\back-novo\\dbcamp-estoque-app:/src:rw"
    working_dir: "/app"
